name: domi_cafe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Flutter UI
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  floating_frosted_bottom_bar: ^0.0.1

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # Google Sign-In
  google_sign_in: ^6.1.2

  # Image picker
  image_picker: ^1.1.0

  # Functional programming helper
  dartz: ^0.10.1
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.3
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
